---
book_repo: pivotal-cf/docs-book-buildservice
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-build-service
    ref: 'master'
  directory: build-service/0-1-0
  subnav_template: buildservice_subnav-0-1-0.erb
  product_info:
    use_local_header: true
    latest_stable_version: '0.1.0'
    changelog_href:
    local_header_img: /images/cloud_rings.png
    local_header_title: Tanzu Build Service (Beta)
    search_placeholder: Search Tanzu Build Service
    url_prefix: build-service/0-1-0
    local_product_version: '0-1-0'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/build-service/0-0-4
        display_name: v0.0.4
      - url_prefix: https://docs.pivotal.io/build-service/0-0-3
        display_name: v0.0.3
