---
book_repo: pivotal-cf/docs-book-buildservice
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-build-service
    ref: 'master'
  directory: platform/build-service/0-0-4
  subnav_template: buildservice_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '0.0.4'
    changelog_href:
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Build Service (Alpha)
    search_placeholder: Search Pivotal Build Service
    url_prefix: platform/build-service/0-0-4
    local_product_version: '0.0.4'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs-pcf-staging.cfapps.io/platform/build-service/0-0-3
        display_name: v0.0.3
