---
template_variables:
  book_title: Pivotal Documentation
  book_title_short: Pivotal Docs
  title: <span class="title-deemph">Pivotal</span> Documentation
  hero_text: "Detailed documentation to help you install, understand, and succeed with Pivotal's enterprise-grade software."
  product_name: Pivotal Platform
  product_url: https://network.pivotal.io/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/pivotal-cf">Back to Product Page</a></div>
  support_link: <a href="http://support.pivotal.io" target="_blank">Support</a>
  support_call_to_action: <a href="http://support.pivotal.io" target="_blank">Need Support?</a>
  support_url: http://support.pivotal.io
  use_global_header: true
  global_header_product_href: https://network.pivotal.io/
  global_header_product_link_text: Downloads

  gtm_account_id: GTM-MM86KCJ

# Global product variables
  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf
  ops_manager_full: Pivotal Operations Manager
  ops_manager: Ops Manager
  app_runtime_full: Pivotal Application Service
  segment_runtime_full: Pivotal Isolation Segment
  app_runtime_abbr: PAS
  app_runtime_abbr_lc: pas
  windows_runtime_full: Pivotal Application Service for Windows
  windows_runtime_abbr: PASW
  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI

# Local product variables
  version_for_link: 0-2-0

# Book content variables
  recommended_by: Pivotal
